# Generated by Django 3.0 on 2019-12-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
