# Generated by Django 3.0 on 2019-12-17 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuido', '0002_auto_20191215_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLA',
            fields=[
                ('cla_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.SmallIntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHERS')])),
                ('primary_language', models.CharField(max_length=255)),
                ('seconday_language', models.CharField(max_length=255)),
                ('tertiary_language', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cuido_lifestyle_aficionados',
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cuido.User')),
            ],
            options={
                'db_table': 'user_credentials',
            },
        ),
    ]
