# Generated by Django 3.0 on 2019-12-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuido', '0004_auto_20191217_1856'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='userfeedback',
            table='user_feedback',
        ),
    ]
